detect:
  weight: "resources/BR-B_work-3/weights/yolov8n.hef"
  score_threshold: 0.3

ipcamera:
  url1: "rtsp://admin:dlsvmfk2849%40@192.168.20.21:554/Streaming/Channels/101"
  url2: null

gates:
  inputs: ["house_in_a"]
  outputs: ["inspector_out_a"]
  weighers: ["weigher_a"]
  exit_event_when_removed: True
  map:
    imagedb_out: house_in_a

network:
  notifier: { host: "192.168.20.10", port: 5000 }
  listener: { host: "192.168.20.10", port: 5000 }
  local:    { host: "192.168.20.11", port: 5000 }

valid_time:
  branch_in: { threshold: 3, error_margin: 0.5 }

  house_in_a: { threshold: 5, error_margin: 0.5 }
  house_in_b: { threshold: 7, error_margin: 0.5 }

  join_in_a: { threshold: 10, error_margin: 0.5 }
  join_in_b: { threshold: 10, error_margin: 0.5 }