camera_id: inspector_a

detect:
  weight: "/home/tracking-br-c-1-new/04_BadRubber/resources/detect/_intergrated/work/2026-06-11T20-02-22/train/weights/yolov8n.hef" # E052
  score_threshold: 0.5

tracker:
  area_threshold: 60000

classifier:
  model_path: ~

ipcamera:
  width: 1920
  height: 1080
  fps: 15
  url1: "rtsp://admin:dlsvmfk2849%40@192.168.20.61:554/Streaming/Channels/101"

gates:
  inputs: ["house_in_a"]
  input_blocks: ["inspector_out_a"]
  outputs: ["inspector_out_a"]
  weighers: ["weigher_a"]

network:
  client:
    - bind: "192.168.20.52"
      host: "192.168.20.50"
      port: 5000
      listen: { enabled: true, types: ["track_event_count_reset", "track_external_id_reset"] }
      notify: { enabled: true, types: ["track_event_movement", "track_event_count", "track_ids_cleared"] }
    - bind: "192.168.20.52"
      host: "192.168.20.51"
      port: 5000
      listen: { enabled: true, types: ["track_event_movement"] }
      notify: { enabled: false, types: [] }
  server:
      bind: "192.168.20.52"
      port: 5000
      types: ["track_event_movement"]


idmanager:
  device_fallback_id: 10

event_image_saver:
  enabled: true
  enabled_event_prefixes:
    created: ["001001", "001002"]
    removed: ~ # all

valid_time:
  house_in_a:
#    enabled: true
#    min_create_seconds: 8
#    max_create_seconds: 180
    enabled: true
    dynamic: { enabled: true, min_sample_count: 3, max_sample_count: 30 }
    min_create_seconds: 8
    max_create_seconds: 13
    margin_seconds: # fixed
      FIFO:  {lower: 2.0, upper: 300.0} # min_external_interval 미설정 시 의미X
      VALID: {lower: 2.0, upper: 3}

sync:
  time:
    house_in_a:
      enabled: True
      id_reset: false
      external_event_type: "id_added_branch_out_a"
      internal_event_type: "created_house_in_a"
      active_target_zone: ["house_in_a"]
      max_queue_size: 6
      valid_queue_size: 3
