detect:
  weight: "resources/SSBR_split-6/weights/yolov8n.hef"
  score_threshold: 0.9

ipcamera:
  url1: "rtsp://admin:dlsvmfk2849%40@192.168.20.23:554/Streaming/Channels/101"
  url2: null

gates:
  inputs: ["split_in"]
  outputs: ["split_out_a", "split_out_b"]
  weighers: []

post_processor:
  exit_event_when_removed: False

network:
  listener: { host: "192.168.20.10", port: 5000 }
  notifier: { host: "192.168.20.10", port: 5000 }
  local:    { host: "192.168.20.11", port: 5000 }
