detect:
  weight: "resources/detect/SSBR_merged_work-A-4+work-B-2/weights/yolov8n.hef"
  score_threshold: 0.9

classifier:
  model_path: "resources/classify/SSBR_classify_251208_2_edit_448/weights/best.pt"
  conf_threshold: 0.95

ipcamera:
  width: 1280
  height: 720
  fps: 15
  url1: "rtsp://admin:dlsvmfk2849%40@192.168.20.21:554/Streaming/Channels/101"
  url2: "rtsp://admin:dlsvmfk2849%40@192.168.20.22:554/Streaming/Channels/101"

gates:
  inputs: ["house_in_a", "house_in_b"]
  outputs: ["inspector_out_a", "inspector_out_b"]
  weighers: ["weigher_a", "weigher_b"]
  classify: ["classify_a", "classify_b"]

network:
  notifier: { host: "192.168.20.10", port: 5000 }
  listener: { host: "192.168.20.11", port: 5000 }
  local:    { host: "192.168.20.12", port: 5000 }

valid_time:
  house_in_a: { threshold: 0.8, error_margin: 0.1 }
  house_in_b: { threshold: 9, error_margin: 1 }

sync:
  baler:
    enabled: True
    a:
      external_event_type: "id_added_branch_out_a"
      internal_event_type: "final_baler_house_in_a"
      active_target_zone: ["weigher_in_a"]
    b:
      external_event_type: "id_added_branch_out_b"
      internal_event_type: "final_baler_house_in_b"
      active_target_zone: ["weigher_in_b"]