detect:
  weight: "resources/SSBR_split-6/weights/yolov8n.hef"
  score_threshold: 0.9

ipcamera:
  url1: "rtsp://admin:dlsvmfk2849%40@192.168.20.23:554/Streaming/Channels/101"
  url2: null

stream:
  exit_event_when_removed: False

gates:
  inputs: ["branch_in"]
  outputs: ["branch_out_a", "branch_out_b"]
  weighers: []

network:
  listener: { host: "192.168.20.10", port: 5000 }
  notifier: { host: "192.168.20.10", port: 5000 }
  local:    { host: "192.168.20.11", port: 5000 }

valid_time:
  branch_in: { threshold: 7.5, error_margin: 1.5 }

sync:
  time:
    enabled: True
    external_zone: "imagedb_in"
    internal_zone: "branch_in"