id: "SSBR_work-A"

detect:
  weight: "resources/SSBR_merged_work-A-4+work-B-2/weights/yolov8n.hef"
  classes:
    0: "rubber"
  score_threshold: 0.9

ipcamera:
  url1: rtsp://admin:dlsvmfk2849%40@192.168.0.195:554/Streaming/Channels/101
  url2: rtsp://admin:dlsvmfk2849%40@192.168.0.196:554/Streaming/Channels/101
  width: 640
  height: 360
  fps: 25
  format: "RGB"
  thread_interval: 0.03

log_dir:
  root: "logs"
  temp: "temp"

thread:
  min_interval: 0.001
  join_timeout: 2.0

detection_queue:
  max_size: 300
  logging_interval: 3
  get_timeout: 0.01

post_processor:
  thread_interval: 0
  draw_bboxes: false
  draw_masks: false
  draw_texts: false

recorder:
  save_root: "results"
  save_frames: True

tracker:
  iou_threshold: 0.01
  old_threshold: 3
  scale_w: 1
  scale_h: 1

gates:
  masks:
    in1: "masks/SSBR_work-A+B/SSBR_work-A_in.png"
    in2: "masks/SSBR_work-A+B/SSBR_work-B_in.png"
    out1: "masks/SSBR_work-A+B/SSBR_work-A_out.png"
    out2: "masks/SSBR_work-A+B/SSBR_work-B_out.png"

  names:
    in1: "SSBR_work-A_in"
    in2: "SSBR_work-B_in"
    out1: "SSBR_work-A_out"
    out2: "SSBR_work-B_out"