id: "SSBR_work-A"

detect:
  weight: "resources/weights/SSBR_merged_work-A-4+work-B-2/weights/yolov8n.hef"
  classes:
    0: "rubber"
  score_threshold: 0.9

ipcamera:
  url1: "resources/videos/SSBR_work-A/175_part_003.mp4"
  url2: "resources/videos/SSBR_work-B/177_part_003.mp4"
  width: 640
  height: 360
  fps: 25
  format: "RGB"
  thread_interval: 0.03

gates:
  mask_root: "masks/SSBR"
  names:
    in1: "WORK_IN_A"
    in2: "WORK_IN_B"
    out1: "WORK_OUT_A"
    out2: "WORK_OUT_B"

idmanager:
  client:
    host: "127.0.0.1"
    port: 5000
  server:
    host: "127.0.0.1"
    port: 5001
  thread_interval: 0.03

drawer:
  draw: True
  record: True
  
log_dir:
  root: "logs"
  temp: "temp"

thread:
  min_interval: 0.001
  join_timeout: 2.0

detection_queue:
  max_size: 300
  logging_interval: 3
  get_timeout: 0.01

post_processor:
  thread_interval: 0

recorder:
  save_root: "results"
  save_frames: True

tracker:
  iou_threshold: 0.01
  old_threshold: 3
  scale_w: 1
  scale_h: 1