detect:
  sources: [local_test_cam1, local_test_cam2]
  merge:
    mode: vertical
  
  hef_path: resources/detect/SSBR/work/F1038/SSBR_work_F1038_2512181016/weights/yolov8n.hef
  score_threshold: 0.8

  queue_max_size: 300