detect:
  classes:
    0: "rubber"
  weight: ~
  score_threshold: ~
  video_source: "user_appsrc"

ipcamera:
  width: 640
  height: 360
  fps: 25
  format: "RGB"
  thread_interval: 0.00
  url1: ~
  url2: ~
  blocked: ~

log_dir:
  root: "logs"
  process: "process"
  monitor: "monitor"

thread:
  min_interval: 0.001
  join_timeout: 2.0

detection_queue:
  max_size: 300
  logging_interval: 3
  get_timeout: 0.01