detect:
  classes:
    0: "rubber"
  weight: ~
  score_threshold: ~

classifier:
  imgsz: 448
  model_path: ~
  class_names: ~
  buffer_size: 100
  cls_limit: 20
  conf_threshold: 0.95

bbox_capture:
  wr: 1.0
  hr: 1.0
  save: False
  save_dir: "results/captures"

ipcamera:
  width: 640
  height: 360
  fps: 25
  format: "RGB"
  thread_interval: 0.00
  url1: ~
  url2: ~
  blocked: ~
  blank: 0

stream:
  exit_event_when_removed: True
  weigher_delay: 0
  weigher_speed_threshold_max: 80 # pixels per second
  weigher_speed_threshold_min: 10 # pixels per second
  weigher_must_finalized: False

gates:
  mask_root: ~
  inputs: []
  input_blocks: []
  outputs: [] 
  weighers: []
  classify: []
  map:
    imagedb_out:  branch_in
    branch_out_a: house_in_a
    branch_out_b: house_in_b
    inspector_out_a: join_in_a
    inspector_out_b: join_in_b
    weigher_a: {'in': 'weigher_in_a', 'out': 'weigher_out_a'}
    weigher_b: {'in': 'weigher_in_b', 'out': 'weigher_out_b'}
  active_file: "gate_active.yaml"

stream_queue:
  active_file: "stream_active.yaml"
  just_one_id_zones: [] # ["branch_in"]

post_processor:
  thread_interval: 0
  containment_threshold: 0.8

idmanager:
  device_fallback_id: ~
  thread_interval: 0.00
  max_create_seconds: 2
  min_create_seconds: ~
  create_retry_delay: 1

recorder:
  save_root: "results"
  draw: ~
  record: ~
  save_frames: ~
  update_interval: 1

log_dir:
  root: "logs"
  process: "process"
  monitor: "monitor"

network:
  notifier: { host: ~, port: ~ }
  listener: []
  local: { host: ~, port: ~ }

thread:
  min_interval: 0.001
  join_timeout: 2.0

detection_queue:
  max_size: 300
  logging_interval: 3
  get_timeout: 0.01

tracker:
  iou_threshold: 0.1
  old_threshold: 10
  scale_w: 1
  scale_h: 1
  age_threshold: 15
  area_threshold: ~

valid_time:
  enabled: ~

  branch_in: { threshold: ~, error_margin: ~ }

  house_in_a: { threshold: ~, error_margin: ~ }
  house_in_b: { threshold: ~, error_margin: ~ }

  join_in_a: { threshold: ~, error_margin: ~ }
  join_in_b: { threshold: ~, error_margin: ~ }

baler:
  unsynced_baler: 11
  create_fallback_baler_no_externals: 10 # not created from external
  classify_fallback_baler: ~ # 12, used only BR-B
  create_fallback_baler_not_input_zone: 13

sync:
  time:
    branch_in:
      enabled: False
      tolerance: 2
      max_queue_size: 7
      valid_queue_size: 4
      mismatch: 1
      external_event_type: ~ # "id_added_imagedb_out"
      internal_event_type: ~ # "created_branch_in"
      active_target_zone: ~ # ["branch_in"]
    join_in_a:
      enabled: False
      tolerance: 5
      max_queue_size: 7
      valid_queue_size: 4
      mismatch: 1
      external_event_type: ~ # "id_added_inspector_out_a"
      internal_event_type: ~ # "created_join_in_a"
      active_target_zone: ~ # ["join_in_a"]
    join_in_b:
      enabled: False
      tolerance: 5
      max_queue_size: 7
      valid_queue_size: 4
      mismatch: 1
      external_event_type: ~ # "id_added_inspector_out_b"
      internal_event_type: ~ # "created_join_in_b"
      active_target_zone: ~ # ["join_in_b"]

  baler:
    a:
      enabled: False
      max_queue_size: 7
      valid_queue_size: 4
      tolerance: ~
      mismatch: 1
      external_event_type: ~ # "id_added_branch_out_a"
      internal_event_type: ~ # "final_baler_house_in_a"
      active_target_zone: ~ # ["weigher_in_a"]
    b:
      enabled: False
      max_queue_size: 7
      valid_queue_size: 4
      tolerance: ~
      mismatch: 1
      external_event_type: ~ # "id_added_branch_out_b"
      internal_event_type: ~ # "final_baler_house_in_b"
      active_target_zone: ~ # ["weigher_in_b"]

resource_monitor:
  thread_interval: 3
  cpu_interval: 0.5
  cpu_threshold: 80 # %
  ram_threshold: 80 # %
  disk_threshold: 80 # %

voltage_monitor:
  logging_interval: 3
  thread_interval: 0.01
  max_queue_size: 300
