detect:
  classes:
    0: "rubber"
  weight: ~
  score_threshold: ~

ipcamera:
  width: 640
  height: 360
  fps: 25
  format: "RGB"
  thread_interval: 0.00
  url1: ~
  url2: ~

gates:
  default_active: False
  mask_root: "masks/SSBR"
  names:
    in1: ~
    in2: ~
    out1: ~
    out2: ~
    weigher1: ~
    weigher2: ~
  map:
    inspection_out: split_in
    split_out_a: work_in_a
    split_out_b: work_in_b
    work_out_a: merge_in_a
    work_out_b: merge_in_b
  weigher_wait_time: 0.5

post_processor:
  thread_interval: 0
  exit_event_when_removed: False

idmanager:
  thread_interval: 0.00

recorder:
  save_root: "results"
  draw: False
  record: False
  save_frames: False

log_dir:
  root: "logs"
  temp: "temp"

active_listener:
  settings_file: "active.yaml"

network:
  listener: { host: ~, port: ~ }
  notifier: { host: ~, port: ~ }
  local: { host: ~, port: ~ }

thread:
  min_interval: 0.001
  join_timeout: 2.0

detection_queue:
  max_size: 300
  logging_interval: 3
  get_timeout: 0.01

tracker:
  iou_threshold: 0.01
  old_threshold: 3
  scale_w: 1
  scale_h: 1
