id: "SSBR_branch+join"
test_mode: False

recorder:
  save_root: "results"
  draw: False
  record: False
  save_frames: False
  update_interval: 1

valid_time:
  enabled: False

event_counts:
  initial:
    id_added: 0
    created: 0
    weigher_in: 0
    weigher_out: 0
    final_baler: 0
    exited: 0
    removed: 0

gates: {mask_root: "masks/SSBR"}