id: "BR-C_split"
test_mode: False

recorder:
  save_root: "results"
  draw: False
  record: False
  save_frames: False
  update_interval: 1

valid_time:
  enabled: False

gates: {mask_root: "masks/BR-C"}